insert into diary (date_created,title,description,mood_id,user_id) values ("2021-12-07","horrible","Today is horrible",1,1);
insert into diary (date_created,title,description,mood_id,user_id) values ("2021-12-08","crappy","Today is super crappy",2,1);
insert into diary (date_created,title,description,mood_id,user_id) values ("2021-12-09","could be better","A big better but still discouraged",3,1);
insert into diary (date_created,title,description,mood_id,user_id) values ("2021-12-10","improved","Hmmm - things feel significantly better",4,1);
insert into diary (date_created,title,description,mood_id,user_id) values ("2021-12-11","even more improved","Even more better-er",5,1);
insert into diary (date_created,title,description,mood_id,user_id) values ("2021-12-12","doing snappy","Yeah - lets get some stuff done today",8,1);
insert into diary (date_created,title,description,mood_id,user_id) values ("2021-12-13","slight setback","Ehhh - not as good, but not that bad either",6,1);
insert into diary (date_created,title,description,mood_id,user_id) values ("2021-12-14","all right","Back on the up-and-up",7,1);
insert into diary (date_created,title,description,mood_id,user_id) values ("2021-12-15","fun day","Feel even better than 4 days ago",9,1);
insert into diary (date_created,title,description,mood_id,user_id) values ("2021-12-16","WOW!","Lets roll!",10,1);
insert into diary (date_created,title,description,mood_id,user_id) values ("2021-12-13","below snuff","Things aren't really that bad. Just wish cound be better",4,2);
insert into diary (date_created,title,description,mood_id,user_id) values ("2021-12-14","about same","Not really any significant difference.",4,2);
insert into diary (date_created,title,description,mood_id,user_id) values ("2021-12-15","a bit better","Hmmm - feeling a bit better",6,2);
insert into diary (date_created,title,description,mood_id,user_id) values ("2021-12-16","set back","Back to where I was 2-3 days ago",4,2);
insert into diary (date_created,title,description,mood_id,user_id) values ("2021-12-15","Not bad","No reason to complain today",7,3);
insert into diary (date_created,title,description,mood_id,user_id) values ("2021-12-16","Really Great!","Man - lets go have some fun!",10,3);
